bugfix: sonar build failed at release time (#3387)
* bugfix: sonar build failed on staged release PR

Error:  Failed to execute goal on project kroxylicious-operator-dist: Could not resolve dependencies for project io.kroxylicious:kroxylicious-operator-dist:pom:0.20.0-SNAPSHOT
Error:  dependency: io.kroxylicious:kroxylicious-operator:jar:0.20.0-SNAPSHOT (provided)
Error:  	Could not find artifact io.kroxylicious:kroxylicious-operator:jar:0.20.0-SNAPSHOT

We have one step to build everything but the operator, and one to
build the operator so we can send the coverage/report to different
sonar projects. The non-operator build accidentally included the
operator dist module, which failed as above. We suspect that this hasn't
failed on main due to maven build caches and will address that
separately.

Signed-off-by: Robert Young <robertyoungnz@gmail.com>

* bugfix: clean kroxylicious dependencies after builds

We saw some inconsistent behaviour at release time, where the PR sonar
automation failed due to a missing dependency. We hadn't seen this
failure on main and suspect that it is because the module happened to be
in the build-cache. Once it's in the cache it would likely propagate
through all updates to the build cache.

This change introduces a clean as the final step to all actions that use
the build cache to `rm` kroxylcious dependencies from the local maven
repository. This means they should stop participating in the build cache
and prevent them causing these kind of hidden issues. This may incur
some additional build time, though in theory we are always rebuilding
relevant kroxylicious components.

Signed-off-by: Robert Young <robertyoungnz@gmail.com>

---------

Signed-off-by: Robert Young <robertyoungnz@gmail.com>