new failing IT
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because the return value of "org.apache.kafka.common.message.OffsetFetchRequestData$OffsetFetchRequestGroup.topics()" is null
	at io.kroxylicious.filter.usernamespace.UserNamespaceFilter.lambda$onRequest$56(UserNamespaceFilter.java:1309)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.kroxylicious.filter.usernamespace.UserNamespaceFilter.lambda$onRequest$78(UserNamespaceFilter.java:1301)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.kroxylicious.filter.usernamespace.UserNamespaceFilter.onRequest(UserNamespaceFilter.java:359)
	at io.kroxylicious.proxy.filter.RequestResponseInvoker.onRequest(RequestResponseInvoker.java:20)
	at io.kroxylicious.proxy.filter.SafeInvoker.onRequest(SafeInvoker.java:34)
	at io.kroxylicious.proxy.internal.FilterHandler.dispatchDecodedRequest(FilterHandler.java:269)
	at io.kroxylicious.proxy.internal.FilterHandler.writeDecodedRequest(FilterHandler.java:251)
	at io.kroxylicious.proxy.internal.FilterHandler.write(FilterHandler.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at io.kroxylicious.proxy.internal.FilterHandler.forwardRequest(FilterHandler.java:388)
	at io.kroxylicious.proxy.internal.FilterHandler.handleRequestFilterResult(FilterHandler.java:318)
	at io.kroxylicious.proxy.internal.FilterHandler.lambda$configureRequestFilterChain$12(FilterHandler.java:278)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at io.kroxylicious.proxy.internal.FilterHandler.configureRequestFilterChain(FilterHandler.java:278)
	at io.kroxylicious.proxy.internal.FilterHandler.writeDecodedRequest(FilterHandler.java:259)
	at io.kroxylicious.proxy.internal.FilterHandler.write(FilterHandler.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at io.kroxylicious.proxy.internal.FilterHandler.forwardRequest(FilterHandler.java:388)
	at io.kroxylicious.proxy.internal.FilterHandler.handleRequestFilterResult(FilterHandler.java:318)
	at io.kroxylicious.proxy.internal.FilterHandler.lambda$configureRequestFilterChain$12(FilterHandler.java:278)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at io.kroxylicious.proxy.internal.FilterHandler.configureRequestFilterChain(FilterHandler.java:278)
	at io.kroxylicious.proxy.internal.FilterHandler.writeDecodedRequest(FilterHandler.java:259)
	at io.kroxylicious.proxy.internal.FilterHandler.write(FilterHandler.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at io.kroxylicious.proxy.internal.FilterHandler.forwardRequest(FilterHandler.java:388)
	at io.kroxylicious.proxy.internal.FilterHandler.handleRequestFilterResult(FilterHandler.java:318)
	at io.kroxylicious.proxy.internal.FilterHandler.lambda$configureRequestFilterChain$12(FilterHandler.java:278)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
	at io.kroxylicious.proxy.internal.FilterHandler.configureRequestFilterChain(FilterHandler.java:278)
	at io.kroxylicious.proxy.internal.FilterHandler.writeDecodedRequest(FilterHandler.java:259)
	at io.kroxylicious.proxy.internal.FilterHandler.write(FilterHandler.java:183)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:752)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1036)
	at io.netty.channel.Channel.write(Channel.java:267)
	at io.kroxylicious.proxy.internal.KafkaProxyBackendHandler.forwardToServer(KafkaProxyBackendHandler.java:168)
	at io.kroxylicious.proxy.internal.ProxyChannelStateMachine.messageFromClient(ProxyChannelStateMachine.java:347)
	at io.kroxylicious.proxy.internal.ProxyChannelStateMachine.onClientRequest(ProxyChannelStateMachine.java:369)
	at io.kroxylicious.proxy.internal.KafkaProxyFrontendHandler.channelRead(KafkaProxyFrontendHandler.java:246)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.kroxylicious.proxy.internal.ResponseOrderer.channelRead(ResponseOrderer.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1429)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:543)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.handle(AbstractKQueueChannel.java:406)
	at io.netty.channel.kqueue.KQueueIoHandler$DefaultKqueueIoRegistration.handle(KQueueIoHandler.java:472)
	at io.netty.channel.kqueue.KQueueIoHandler.processReady(KQueueIoHandler.java:214)
	at io.netty.channel.kqueue.KQueueIoHandler.run(KQueueIoHandler.java:276)
	at io.netty.channel.SingleThreadIoEventLoop.runIo(SingleThreadIoEventLoop.java:225)
	at io.netty.channel.SingleThreadIoEventLoop.run(SingleThreadIoEventLoop.java:196)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:1193)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Signed-off-by: Keith Wall <kwall@apache.org>