bugfix: sonar build failed on staged release PR
Error:  Failed to execute goal on project kroxylicious-operator-dist: Could not resolve dependencies for project io.kroxylicious:kroxylicious-operator-dist:pom:0.20.0-SNAPSHOT
Error:  dependency: io.kroxylicious:kroxylicious-operator:jar:0.20.0-SNAPSHOT (provided)
Error:  	Could not find artifact io.kroxylicious:kroxylicious-operator:jar:0.20.0-SNAPSHOT

We have one step to build everything but the operator, and one to
build the operator so we can send the coverage/report to different
sonar projects. The non-operator build accidentally included the
operator dist module, which failed as above. We suspect that this hasn't
failed on main due to maven build caches and will address that
separately.

Signed-off-by: Robert Young <robertyoungnz@gmail.com>